name: flutter_faking_server_data
description: A small sample to demo a way of faking server data.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
  build_runner: ^1.10.6
  json_serializable: ^3.5.0
  fake_http_client: ^0.0.3
  http_archive: ^0.1.0

flutter:
  uses-material-design: true

  assets:
    - test_resources/ # TODO: exclude from prod builds (automate it with a script)
